index:
    path: /
    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_studies:
    path: /studies
    controller: App\Controller\StudiesController::index
