index:
    path: /
    controller: App\Controller\DefaultController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
# Studies #
app_studies_index:
    path: /studies
    controller: App\Controller\StudiesController::index
app_studies_new:
    path: /studies/new
    controller: App\Controller\StudiesController::new
app_studies_edit:
    path: /studies/{id}/edit
    controller: App\Controller\StudiesController::edit
app_studies_delete:
    path: /studies/{id}/delete
    controller: App\Controller\StudiesController::delete
# Documentations #
app_documentations_index:
    path: /documentations
    controller: App\Controller\DocumentationsController::index
app_documentations_new:
    path: /documentations/new
    controller: App\Controller\DocumentationsController::new
app_documentations_edit:
    path: /documentations/{id}/edit
    controller: App\Controller\DocumentationsController::edit
app_documentations_delete:
    path: /documentations/{id}/delete
    controller: App\Controller\DocumentationsController::delete
app_documentations_show:
    path: '/documentations/doc/{id}'
    controller: 'App\Controller\DocumentationsController::show'
# Documentations Category #
# app_document_category_index:
#     path: /documentcategory
#     controller: App\Entity\DocumentCategoryController::index
# app_document_category_new:
#     path: /documentcategory/new
#     controller: App\Entity\DocumentCategoryController::new
# app_document_category_edit:
#     path: /documentcategory/{id}/edit
#     controller: App\Entity\DocumentCategoryController::edit
# app_document_category_delete:
#     path: /documentcategory/{id}/delete
#     controller: App\Entity\DocumentCategoryController::delete
app_document_category:
    resource: ../src/Controller/DocumentCategoryController.php
    type: annotation
app_administration:
    resource: ../src/Controller/AdministrationController.php
    type: annotation